## Hugging Face EDA

In [1]:
import pandas as pd

In [10]:
data = pd.read_parquet('../data/hugging/train-00000-of-00006-1d1ab78e9df29da3.parquet',engine='pyarrow')
data2 = pd.read_parquet('../data/hugging/train-00001-of-00006-e144d158479ea86c.parquet',engine='pyarrow')
data3 = pd.read_parquet('../data/hugging/train-00002-of-00006-4c4e11648a08b217.parquet',engine='pyarrow')
data4 = pd.read_parquet('../data/hugging/train-00003-of-00006-2a1abb581d15b61e.parquet',engine='pyarrow')
data5 = pd.read_parquet('../data/hugging/train-00004-of-00006-88eb978982946f67.parquet',engine='pyarrow')
data6 = pd.read_parquet('../data/hugging/train-00005-of-00006-3b07ebebf92f527d.parquet',engine='pyarrow')

In [3]:
data

,text,labels,encoded_labels
0,Football positions \n\nHi Mehudson. When you'...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,Thank you SO MUCH for your Nazi-like oversight...,"[toxic, profane, insult]","[1, 1, 1, 0, 0, 0, 0, 0, 0]"
2,Darkwind \n Stick it up your arse you offensi...,"[toxic, profane]","[1, 1, 0, 0, 0, 0, 0, 0, 0]"
3,Message from you to an IP \n\nI received a mes...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,Misleading and inappropriate citations Used,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
...,...,...,...
1057487,I drove an all-electric Volvo C30 more than fi...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057488,Comey will be paid the remainder of his lucrat...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057489,Poor leadership is prevalent through all segme...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057490,I thought maybe it was to attract a mate.,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057491,"Little off the subject, but has anyone flown o...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [6]:
data2

,text,labels,encoded_labels
0,There wouldn't be a housing crisis in Toronto ...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,"Michael, with modern medicine only a small fra...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,Not utter nonsense at all.\n\nOur Finance Coun...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,"Very sad news indeed, definitely one of the ve...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,Don't forget kid's... our United States Milita...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
...,...,...,...
1057487,¡Bienvenidos!\n\nHola y bienvenidos a Wikipedi...,"[toxic, profane, insult, hate]","[1, 1, 1, 1, 0, 0, 0, 0, 0]"
1057488,Agregué Brown v. Board y la otra decisión que ...,[insult],"[0, 0, 1, 0, 0, 0, 0, 0, 0]"
1057489,"""\n\n¿En serio? Si simplemente me detuviera ca...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057490,"""como, ¿cómo obtengo lo que dice que estoy ret...",[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"
1057491,Liverpool FC\n\nHa habido una alarma cada vez ...,[],"[0, 0, 0, 0, 0, 0, 0, 0, 0]"

In [7]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1057492 entries, 0 to 1057491
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   text            1057492 non-null  object
 1   labels          1057492 non-null  object
 2   encoded_labels  1057492 non-null  object
dtypes: object(3)
memory usage: 24.2+ MB

In [8]:
data2.loc[data2['labels'].apply(lambda x: 'toxic' in x)]

,text,labels,encoded_labels
11,I will vote for a fraud before I vote for a li...,"[toxic, insult]","[1, 0, 1, 0, 0, 0, 0, 0, 0]"
12,Foolish Drumpf. Foolishness is bewailing its e...,"[toxic, insult]","[1, 0, 1, 0, 0, 0, 0, 0, 0]"
29,I guess they're outlining the economic malaise...,"[toxic, insult]","[1, 0, 1, 0, 0, 0, 0, 0, 0]"
34,"you left out suicide bombing, stabbing and cut...",[toxic],"[1, 0, 0, 0, 0, 0, 0, 0, 0]"
38,"Potlicker infant, your obfuscation continues a...","[toxic, insult]","[1, 0, 1, 0, 0, 0, 0, 0, 0]"
...,...,...,...
1057430,Campesino blanco\nNo deberías hablar mal de NA...,[toxic],"[1, 0, 0, 0, 0, 0, 0, 0, 0]"
1057431,"¡Felicidades!\n\n¡Felicitaciones, alma phire, ...",[toxic],"[1, 0, 0, 0, 0, 0, 0, 0, 0]"
1057438,"""\n\n == Firmas 101 ==\n\n ¿Me puedes ayudar? ...",[toxic],"[1, 0, 0, 0, 0, 0, 0, 0, 0]"
1057455,RE: consulta del festival cristiano temprano e...,"[toxic, profane, insult, hate]","[1, 1, 1, 1, 0, 0, 0, 0, 0]"
1057487,¡Bienvenidos!\n\nHola y bienvenidos a Wikipedi...,"[toxic, profane, insult, hate]","[1, 1, 1, 1, 0, 0, 0, 0, 0]"

In [9]:
exploded_labels = data2['labels'].explode()


label_counts = exploded_labels.value_counts()

label_counts

labels
toxic      164555
insult      38814
profane     11356
hate         4390
threat       1572
sexual       1160
Name: count, dtype: int64

In [15]:
# for loop value counts 

tables = [
    data,
    data2,
    data3,
    data4,
    data5,
    data6
]


label_value_counts = []

for table in tables:
    exploded = table['labels'].explode()  
    counts = exploded.value_counts()  
    label_value_counts.append(counts)

In [16]:
label_value_counts

[labels
 toxic      71976
 insult     47478
 profane    11161
 hate        5079
 threat      1833
 sexual      1594
 Name: count, dtype: int64,
 labels
 toxic      164555
 insult      38814
 profane     11356
 hate         4390
 threat       1572
 sexual       1160
 Name: count, dtype: int64,
 labels
 toxic      71406
 insult     47270
 profane     9089
 hate        4943
 threat      1783
 sexual      1662
 Name: count, dtype: int64,
 labels
 toxic      163771
 insult      39057
 profane     13474
 hate         4646
 threat       1622
 sexual       1158
 Name: count, dtype: int64,
 labels
 toxic      67761
 insult     46782
 profane     4522
 hate        4492
 sexual      1834
 threat      1624
 Name: count, dtype: int64,
 labels
 selfharm      247778
 offensive      37329
 toxic          28573
 hate           25889
 insult         17857
 harassment      4072
 profane         1738
 sexual          1521
 threat           631
 Name: count, dtype: int64]

In [19]:
from functools import reduce


combined_counts = reduce(lambda x, y: x.add(y, fill_value=0), label_value_counts)

combined_counts.sort_values(ascending=False, inplace=True)  

combined_counts

labels
toxic         568042.0
selfharm      247778.0
insult        237258.0
profane        51340.0
hate           49439.0
offensive      37329.0
threat          9065.0
sexual          8929.0
harassment      4072.0
Name: count, dtype: float64

In [22]:
data6.loc[data6['labels'].apply(lambda x: 'selfharm' in x)]

,text,labels,encoded_labels
464568,redflag always option anyone says otherwise ne...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
464570,thinking tonight maybe tomorrowi cant live wit...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
464571,redflag sort presentdamn man life hits hard kn...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
464572,redflag something yearn possiblefirst im going...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
464575,holidays ruined without failim envious familie...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
...,...,...,...
1040459,"Eso es todoLo haré hoy.Demasiado cansado, dema...",[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
1040461,"Vine a este sub para la ayuda, pero me hizo aú...",[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
1040462,"Mente, de sabor destructivo.En la inundación d...",[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
1040467,¿Cómo funciona la eutanasia en el belgio? He l...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
1040468,No hay absolutamente ninguna otra opción.Me vo...,[selfharm],"[0, 0, 0, 0, 0, 0, 0, 1, 0]"

The TLDR of the hugging face datasets is that there are 9 different categories in the train and validation datasets.  They are as follows:

- toxic        
- selfharm   
- insult     
- profane     
- hate          
- offensive    
- threat
- sexual
- harassment 

The labels also come pre-encoded so that an algorithm can better identify the labels within the text.  The one issue which I am uncertain at this point whether it would affect our project or not is that the languages are not consistent.  From what I can tell there are several different languages used in the text columns and at this point I'm not entirely certain how to separate them for training purposes.  On the other hand this dataset is pretty strongly optimized for machine learning.  6 training sets and one validation set combined with human legible and machine legible labels means we could probably create a fairly strong toxicity detector from this group.

## Kaggle Bias EDA

In [23]:
all_data = pd.read_csv('../data/kaggle_bias/all_data.csv')

In [25]:
all_data.head()

,id,comment_text,split,created_date,publication_id,parent_id,article_id,rating,funny,wow,...,white,asian,latino,other_race_or_ethnicity,physical_disability,intellectual_or_learning_disability,psychiatric_or_mental_illness,other_disability,identity_annotator_count,toxicity_annotator_count
0,1083994,He got his money... now he lies in wait till a...,train,2017-03-06 15:21:53.675241+00,21,NaN,317120,approved,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,67
1,650904,Mad dog will surely put the liberals in mental...,train,2016-12-02 16:44:21.329535+00,21,NaN,154086,approved,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,76
2,5902188,And Trump continues his lifelong cowardice by ...,train,2017-09-05 19:05:32.341360+00,55,NaN,374342,approved,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,63
3,7084460,"""while arresting a man for resisting arrest"".\...",test,2016-11-01 16:53:33.561631+00,13,NaN,149218,approved,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,76
4,5410943,Tucker and Paul are both total bad ass mofo's.,train,2017-06-14 05:08:21.997315+00,21,NaN,344096,approved,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,80

In [26]:
all_data.columns

Index(['id', 'comment_text', 'split', 'created_date', 'publication_id',
       'parent_id', 'article_id', 'rating', 'funny', 'wow', 'sad', 'likes',
       'disagree', 'toxicity', 'severe_toxicity', 'obscene', 'sexual_explicit',
       'identity_attack', 'insult', 'threat', 'male', 'female', 'transgender',
       'other_gender', 'heterosexual', 'homosexual_gay_or_lesbian', 'bisexual',
       'other_sexual_orientation', 'christian', 'jewish', 'muslim', 'hindu',
       'buddhist', 'atheist', 'other_religion', 'black', 'white', 'asian',
       'latino', 'other_race_or_ethnicity', 'physical_disability',
       'intellectual_or_learning_disability', 'psychiatric_or_mental_illness',
       'other_disability', 'identity_annotator_count',
       'toxicity_annotator_count'],
      dtype='object')

In [27]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999516 entries, 0 to 1999515
Data columns (total 46 columns):
 #   Column                               Dtype
---  ------                               -----
 0   id                                   int64
 1   comment_text                         object
 2   split                                object
 3   created_date                         object
 4   publication_id                       int64
 5   parent_id                            float64
 6   article_id                           int64
 7   rating                               object
 8   funny                                int64
 9   wow                                  int64
 10  sad                                  int64
 11  likes                                int64
 12  disagree                             int64
 13  toxicity                             float64
 14  severe_toxicity                      float64
 15  obscene                              float64
 16  sexual_explicit                      float64
 17  identity_attack                      float64
 18  insult                               float64
 19  threat                               float64
 20  male                                 float64
 21  female                               float64
 22  transgender                          float64
 23  other_gender                         float64
 24  heterosexual                         float64
 25  homosexual_gay_or_lesbian            float64
 26  bisexual                             float64
 27  other_sexual_orientation             float64
 28  christian                            float64
 29  jewish                               float64
 30  muslim                               float64
 31  hindu                                float64
 32  buddhist                             float64
 33  atheist                              float64
 34  other_religion                       float64
 35  black                                float64
 36  white                                float64
 37  asian                                float64
 38  latino                               float64
 39  other_race_or_ethnicity              float64
 40  physical_disability                  float64
 41  intellectual_or_learning_disability  float64
 42  psychiatric_or_mental_illness        float64
 43  other_disability                     float64
 44  identity_annotator_count             int64
 45  toxicity_annotator_count             int64
dtypes: float64(32), int64(10), object(4)
memory usage: 701.7+ MB

In [31]:
all_data.isnull().sum()

id                                           0
comment_text                                 4
split                                        0
created_date                                 0
publication_id                               0
parent_id                               864807
article_id                                   0
rating                                       0
funny                                        0
wow                                          0
sad                                          0
likes                                        0
disagree                                     0
toxicity                                     0
severe_toxicity                              0
obscene                                      0
sexual_explicit                              0
identity_attack                              0
insult                                       0
threat                                       0
male                                   1551516
female                                 1551516
transgender                            1551516
other_gender                           1551516
heterosexual                           1551516
homosexual_gay_or_lesbian              1551516
bisexual                               1551516
other_sexual_orientation               1551516
christian                              1551516
jewish                                 1551516
muslim                                 1551516
hindu                                  1551516
buddhist                               1551516
atheist                                1551516
other_religion                         1551516
black                                  1551516
white                                  1551516
asian                                  1551516
latino                                 1551516
other_race_or_ethnicity                1551516
physical_disability                    1551516
intellectual_or_learning_disability    1551516
psychiatric_or_mental_illness          1551516
other_disability                       1551516
identity_annotator_count                     0
toxicity_annotator_count                     0
dtype: int64

In [34]:
(1551516/1999515)*100 # 77% of data in a lot of columns is null

77.59461669454842

In [35]:
all_data['black'].value_counts() # doesn't appear to be boolean

black
0.000000    426446
1.000000      8448
0.800000      1719
0.833333      1696
0.100000      1390
             ...
0.000645         1
0.950811         1
0.002535         1
0.000566         1
0.003137         1
Name: count, Length: 137, dtype: int64